language: go
sudo: false
dist: trusty
osx_image: xcode8.3
go: 1.11.x

os:
  - linux

cache:
  directories:
    - node_modules

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install upx -y
  - go get github.com/sirupsen/logrus
  - go get gopkg.in/cheggaaa/pb.v2
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/robertkrimen/otto
  - go get github.com/urfave/cli
  - go get github.com/konsorten/go-windows-terminal-sequences || true
  - go get github.com/axgle/mahonia
  - go get github.com/feilongfl/c-get
  
script:
  - sh ./build.sh
  
deploy:
  provider: releases
  api_key: ${githubtoken}
  file:
    - "./build/c-get-linux-amd64"
    - "./build/c-get-linux-arm"
    - "./build/c-get-mac"
    - "./build/c-get-win.exe"
  skip_cleanup: true
  on:
    repo: feilongfl/c-get
    branch:
      - master
    tags: true
