#!/usr/bin/env sh
echo build linux ...
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o c-get-linux .
echo build mac ...
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o c-get-mac .
echo build windows ...
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o c-get-win.exe .
